apiVersion: v1
baseDomain: lo
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 1
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: gw
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  #machineCIDR: 10.0.0.0/16
  #networkType: OpenShiftSDN
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2d3ZXN0cmVkaGF0Y29tMW10NDc1aXN5Z3RtcTRrb2xnaDF1aHNiNDZjOlVUQzNZNDdGRjhSTk1JMzk2R1RPQTIxWTFZVUFNQlQyTzFMUlVKSUI3WUlMVFNYTzBVM1kxODdRUlZPWVg0UFM=","email":"gwest@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2d3ZXN0cmVkaGF0Y29tMW10NDc1aXN5Z3RtcTRrb2xnaDF1aHNiNDZjOlVUQzNZNDdGRjhSTk1JMzk2R1RPQTIxWTFZVUFNQlQyTzFMUlVKSUI3WUlMVFNYTzBVM1kxODdRUlZPWVg0UFM=","email":"gwest@redhat.com"},"registry.connect.redhat.com":{"auth":"NjIxMzM3OHx1aGMtMU10NDc1aXNZR1RNcTRrT2xnaDF1aHNiNDZDOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKbFpHVXlOREV5TkRFNVl6TTBNemd5WW1Rd05XVmtNalkyTldGaVptSXpPQ0o5LkxiTTVUeWRSNDREQVIxY0V1SmxFRTktVjNYYlFhVkppS3ZMZ3ltTW5fYVVRUS1STG00N3J2SEF2SDVpdHV3WV8tNDlrcWkyVDhGVkN0OXJUUkFGRl9TS2lhRkEyb25WSGIzOE1GTGk3TU5OM3ZtbjFOQjBfR1VjUHNuQmxzZ1lGNW1haFFCLXF1bFFlZWtobzQwT1E2UGdHeTBvTWNaU1NXbjRWWkljeTJCMjFzbEwwQzM1WGR5WlZjc0FpTnRtLS1DS1F2RFFYbV9MR2tOWl9Xblc0d05PYkVDeVRMSHJESlpOc2lHQjJ1eGhKVndwc3Vrb21Mc1BjdnZEamV3UjFqT1E0cEdwOGJXcDdvbC1JUVhjd05sNHdEakpKV0hzTlFuY3l1UUhBTW5USExUd3FVcmVtZG13ZEUtSF9fS3FUQUFFR3hjbGJBSGlXVmppWVBBU0JyZ2RiWUtrcHMzM2hNMnR3SE5DcVdPWnZTR3lQVXQ1bGcyakxueDdnX2ZEUE9jYlRQZjdtZXBMTG8tMk1fV1EydWlBUVVnRF9ZQ1pCejFNN1dfdGdXZFo2MHBDLXpjTExCUkE1dnNGRlVUVmgzQXhLNE5vTm5IQkd4YWE4cUhVX0ZBX2lxMWpFaEZKVVpjR21wUlpNbVhwVVdpYTVtblkwVWVXUWczZTNCT04yMTdlRGl0Y0VsY1MzZFdRYmt1Vk1qZ0NuMVNrY0o2TlZJdUVHa1ZfX3AycDkzei00MjNOSXh4MjNKM0VmaHVQYUJVcDctM180UHBzZ3h5UGVTNlNJanJLeGotYzBXUk84d28xT3diTW9aUlc3RDRycU00dDJueXlNWEkwUVlfQmFaclVsaThEaGFJMlRIZEJLc0VXRF9KaTNMM2JOdExHX2d1cDVWRzVtWGpv","email":"gwest@redhat.com"},"registry.redhat.io":{"auth":"NjIxMzM3OHx1aGMtMU10NDc1aXNZR1RNcTRrT2xnaDF1aHNiNDZDOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKbFpHVXlOREV5TkRFNVl6TTBNemd5WW1Rd05XVmtNalkyTldGaVptSXpPQ0o5LkxiTTVUeWRSNDREQVIxY0V1SmxFRTktVjNYYlFhVkppS3ZMZ3ltTW5fYVVRUS1STG00N3J2SEF2SDVpdHV3WV8tNDlrcWkyVDhGVkN0OXJUUkFGRl9TS2lhRkEyb25WSGIzOE1GTGk3TU5OM3ZtbjFOQjBfR1VjUHNuQmxzZ1lGNW1haFFCLXF1bFFlZWtobzQwT1E2UGdHeTBvTWNaU1NXbjRWWkljeTJCMjFzbEwwQzM1WGR5WlZjc0FpTnRtLS1DS1F2RFFYbV9MR2tOWl9Xblc0d05PYkVDeVRMSHJESlpOc2lHQjJ1eGhKVndwc3Vrb21Mc1BjdnZEamV3UjFqT1E0cEdwOGJXcDdvbC1JUVhjd05sNHdEakpKV0hzTlFuY3l1UUhBTW5USExUd3FVcmVtZG13ZEUtSF9fS3FUQUFFR3hjbGJBSGlXVmppWVBBU0JyZ2RiWUtrcHMzM2hNMnR3SE5DcVdPWnZTR3lQVXQ1bGcyakxueDdnX2ZEUE9jYlRQZjdtZXBMTG8tMk1fV1EydWlBUVVnRF9ZQ1pCejFNN1dfdGdXZFo2MHBDLXpjTExCUkE1dnNGRlVUVmgzQXhLNE5vTm5IQkd4YWE4cUhVX0ZBX2lxMWpFaEZKVVpjR21wUlpNbVhwVVdpYTVtblkwVWVXUWczZTNCT04yMTdlRGl0Y0VsY1MzZFdRYmt1Vk1qZ0NuMVNrY0o2TlZJdUVHa1ZfX3AycDkzei00MjNOSXh4MjNKM0VmaHVQYUJVcDctM180UHBzZ3h5UGVTNlNJanJLeGotYzBXUk84d28xT3diTW9aUlc3RDRycU00dDJueXlNWEkwUVlfQmFaclVsaThEaGFJMlRIZEJLc0VXRF9KaTNMM2JOdExHX2d1cDVWRzVtWGpv","email":"gwest@redhat.com"}}}'
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWUsb0I159v27vSBuOOyQMX54iD2zuKZOOy+e5GRCJ3yONNr3Mkdyng67BNfsnvlf8kpgSi0yiaVGeXKSjkrY9YPHe0wkVW0UHZ9uZqYqgVdEzSG3Z0NNkrd/zp3jCztPad+q6iWb1R0iFlK7/h8NihOky9HXOustrtDwnvTgONwJnluxQp1zl86deKP0W9xx3Ky/Jobr3dbfOhJVK3qzF6OL6KaNjpT+hDYjh1OISzrx1jWLxFvZ4r7X2wbRhcNRyD5sTrxcs3z5Xdz/KRT0UhIj47CF4Heoiqtl/aQ5kdjpRqlmC2spJ9WZinsqbb6HhZ1i8Yd2ZycDQZF+S8n1n
  gwest@Glenns-MacBook-Pro.local
